In [2]:
import numpy as np

In [3]:
a = np.array([[1],
              [2],
              [3]])

b = np.array([[10, 20, 30, 40]])

print(a.shape)
print(b.shape)

print(a + b)

(3, 1)
(1, 4)
[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


In [4]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[10, 20],
              [30, 40]])

print(a * b)

[[ 10  40]
 [ 90 160]]


In [5]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[10, 20],
              [30, 40]])

print(np.dot(a, b))

[[ 70 100]
 [150 220]]


In [6]:
x = np.array([2, 4, 6, 8, 10])

print("sum:", np.sum(x))
print("mean:", np.mean(x))
print("std:", np.std(x))
print("var:", np.var(x))

sum: 30
mean: 6.0
std: 2.8284271247461903
var: 8.0


In [8]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [9]:
result = 0

for i in range(len(a)):
    result += a[i] * b[i]

print(result)

32


In [10]:
print(np.dot(a, b))

32


In [11]:
x = np.array([10, 20, 30, 40, 50])
print(x[[0, 2, 4]])

[10 30 50]


In [14]:
x = np.array([10, 20, 30, 40, 50])
print(x > 25)
print(x[x > 25])

[False False  True  True  True]
[30 40 50]
