In [1]:
import numpy as np
X = np.array([1000, 1500, 2000, 2500])
y = np.array([40, 60, 80, 100])

In [2]:
X_b = np.c_[np.ones(len(X)), X]

In [3]:
np.ones(4)

array([1., 1., 1., 1.])

In [4]:
X_b

array([[1.0e+00, 1.0e+03],
       [1.0e+00, 1.5e+03],
       [1.0e+00, 2.0e+03],
       [1.0e+00, 2.5e+03]])

In [5]:
theta = np.linalg.inv(X_b.T @ X_b) @ X_b.T @ y

In [6]:
X_b.T

array([[1.0e+00, 1.0e+00, 1.0e+00, 1.0e+00],
       [1.0e+03, 1.5e+03, 2.0e+03, 2.5e+03]])

In [7]:
import numpy as np

# 1. Training data
X = np.array([1000, 1500, 2000, 2500])
y = np.array([40, 60, 80, 100])

# 2. Add a column of 1s for the intercept
X_b = np.c_[np.ones(len(X)), X]

# 3. Normal Equation
theta = np.linalg.inv(X_b.T @ X_b) @ X_b.T @ y

# 4. Extract parameters
b = theta[0]
m = theta[1]

print("Intercept:", b) 
print("Slope:", m)

# 5. Make predictions
predictions = X_b @ theta

print("Predictions:", predictions)

# 6. Calculate MSE
mse = np.mean((y - predictions) ** 2)

print("MSE:", mse)

# 7. Calculate R²
sse = np.sum((y - predictions) ** 2)
sst = np.sum((y - np.mean(y)) ** 2)

r2 = 1 - (sse / sst)

print("R²:", r2)

# 8. Predict a new house
new_house = np.array([[1, 3000]])

new_prediction = new_house @ theta

print("Predicted price for 3000 sq ft:",
      new_prediction[0])

Intercept: 8.526512829121202e-14
Slope: 0.039999999999999994
Predictions: [ 40.  60.  80. 100.]
MSE: 5.5788243217229955e-27
R²: 1.0
Predicted price for 3000 sq ft: 120.00000000000007


In [12]:
import numpy as np
import pandas as pd


# 1. Load the dataset
df = pd.read_csv("real_estate_dataset.csv")


# 2. Select input and target
X = df["Square_Feet"].values
y = df["Price"].values


# 3. Add a column of 1s for the intercept
X_b = np.c_[np.ones(len(X)), X]


# 4. Calculate theta using Normal Equation
theta = np.linalg.inv(X_b.T @ X_b) @ X_b.T @ y


# 5. Get intercept and slope
b = theta[0]
m = theta[1]


# 6. Make predictions
predictions = X_b @ theta


# 7. Calculate MSE
mse = np.mean((y - predictions) ** 2)


# 8. Calculate R²
sse = np.sum((y - predictions) ** 2)
sst = np.sum((y - np.mean(y)) ** 2)

r2 = 1 - (sse / sst)


# 9. Display results
print("Intercept (b):", b)
print("Slope (m):", m)
print("MSE:", mse)
print("R²:", r2)


# 10. Predict price for a new house
new_house = np.array([[1, 10000]])

new_prediction = new_house @ theta

print("Predicted price for 10000 square feet:", new_prediction[0])

Intercept (b): 422466.5157033011
Slope (m): 914.6972187433406
MSE: 10264997905.211082
R²: 0.31203805576206745
Predicted price for 10000 square feet: 9569438.703136709
