In [1]:
import numpy as np

In [2]:
arr=np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [3]:
print(arr.shape)
print(arr.dtype)

(5,)
int64


In [4]:
print(arr[0])
print(arr[-1])
print(arr[2])

10
50
30


In [5]:
print(arr[1:4])
print(arr[0:])
print(arr[3:])

[20 30 40]
[10 20 30 40 50]
[40 50]


In [7]:
a=np.zeros(5)
b=np.ones(5)
c=np.arange(1,11)
print(a)
print(b)
print(c)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[ 1  2  3  4  5  6  7  8  9 10]


In [8]:
print(arr+10)
print(arr*2)
print(arr-5)
print(arr/10)

[20 30 40 50 60]
[ 20  40  60  80 100]
[ 5 15 25 35 45]
[1. 2. 3. 4. 5.]


In [9]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
print(matrix.shape)
print(matrix.dtype)
print(matrix[0,1])
print(matrix[2,2])

(3, 3)
int64
2
9


In [11]:
print(matrix[0,:])
print(matrix[:,0])
print(matrix[0:2,1:3])

[1 2 3]
[1 4 7]
[[2 3]
 [5 6]]


In [12]:
print(matrix+10)
print(matrix*2)
print(matrix-5)
print(matrix/1)

[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[-4 -3 -2]
 [-1  0  1]
 [ 2  3  4]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [15]:
print(matrix.sum())
print(matrix.mean())
print(matrix.max())
print(matrix.min())

45
5.0
9
1


In [16]:
print(matrix.sum(axis=0))
print(matrix.sum(axis=1))

[12 15 18]
[ 6 15 24]


In [17]:
matrix=np.arange(1,10).reshape(3,3)
print(matrix)
print(matrix.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [18]:
print(matrix.flatten())
print(matrix.ravel())

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [19]:
arr=np.array([1,2,3,4,5,6])
print(arr.reshape(2,3))
print(arr.reshape(3,2))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [20]:
matrix=np.array([[1,2,3],[4,5,6]])
print(matrix)
print(matrix.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [21]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.concatenate((a,b)))

[1 2 3 4 5 6]


In [28]:
a = np.array([[1,2],
              [3,4]])

b = np.array([[5,6],
              [7,8]])

print(np.concatenate((a,b), axis=0))
print(np.concatenate((a,b), axis=1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [29]:
a = np.array([1, 2, 3, 4])

b = a.copy()

b[0] = 100

print(a)
print(b)

[1 2 3 4]
[100   2   3   4]


In [30]:
a = np.array([1, 2, 3, 4])

b = a.view()

b[0] = 100

print(a)
print(b)

[100   2   3   4]
[100   2   3   4]


In [31]:
a = np.array([10, 20, 30, 40])

a[0] = 99

print(a)

[99 20 30 40]


In [32]:
a = np.array([10, 25, 5, 40])

np.where(a > 20, 1, 0)

array([0, 1, 0, 1])

In [33]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.dot(a, b)

np.int64(32)